### ISSUE TITLE
Redirect issue

### ISSUE THREAD

**Issue by gynter** [ngTrash/old-blog#1]
http://www.georgenetu.com redirects to http://georgenetu.com and http://georgenetu.com redirects back to http://www.georgenetu.com which causes infinite loop.

```
$ curl -I http://www.georgenetu.com/index.html
HTTP/1.1 301 Moved Permanently
Server: GitHub.com
Content-Type: text/html
Location: http://georgenetu.com/index.html
Content-Length: 178
Accept-Ranges: bytes
Date: Sat, 17 Oct 2015 21:38:41 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-ams4140-AMS
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1445117921.366906,VS0,VE82
Vary: Accept-Encoding
```

```
$ curl -I http://georgenetu.com/index.html
HTTP/1.1 302 Moved Temporarily
Server: nginx/1.0.15
Date: Sat, 17 Oct 2015 21:38:02 GMT
Content-Type: text/html
Connection: keep-alive
Keep-Alive: timeout=15
Content-Length: 154
Location: http://www.georgenetu.com/index.html
```

**Comment by georgenetu** [comment]
Here are my DNS records:
![991afe8d0323ec74db37b18b456d130e](https://cloud.githubusercontent.com/assets/3518650/10561992/8996abe4-754d-11e5-8ce8-a40ceae23a4e.png)
I get either 404 or ERR_TOO_MANY_REDIRECTS when I go to georgenetu.com

**Comment by gynter** [comment]
This is not a DNS issue, You need to change the domain to www.georgenetu.com in CNAME.
